### PR TITLE
Permissions/Kicking Members/Alliance wide messages

### PR DESCRIPTION
**Pull request by shibdib**
Added the ability to set "leaders" whom are the only ones who can kick/invite/alter alliance info/send a message to all alliance members via api.

### CODE REVIEW

**Comment by shibdib** [comment]
I do not have anywhere available to install a dev version to test this. I'm fairly confident about everything except for the SQL comment you can see on a commit above.

**Comment by tedivm** [comment]
Rather than having a new column for the "Leader" you should create a new table called "leaders" with a column for alliances and another column for the player. This would allow alliances to have more than one leader.

**Comment by shibdib** [comment]
The leader column is an int array and it's setup to allow multiple leaders. I could make a separate table but that seems unnecessary when a column will suffice. 

And I'm not familiar with vagrant and don't really have the motivation to become familiar with it for this pr tbh 🤷‍♂️

**Comment by tedivm** [comment]
You literally just have to install vagrant and then follow the instructions on the README of this project- you don't need to know much about vagrant at all.

From my understanding using an array column for this isn't really appropriate for a foreign key column (please correct me if I'm wrong here, as this isn't an area I'm all that used to). 

https://stackoverflow.com/questions/41054507/postgresql-array-of-elements-that-each-are-a-foreign-key

Also, according to the postgres website-

> Tip: Arrays are not sets; searching for specific array elements can be a sign of database misdesign. Consider using a separate table with a row for each item that would be an array element. This will be easier to search, and is likely to scale better for a large number of elements.

Both of this issues come up in the scenario of a user being deleted from the database or being removed from an alliance. If a user removes themselves from an alliance we'd have to search for and remove that user from any leadership positions they are in (ie, search for specific array elements) and if the user gets removed (which happens when the admins help users change their usernames) we wouldn't be able to rely on the relationship cascading the delete.

**Comment by shibdib** [comment]
I'm not understanding the issue

```    leader_list = alliance['leader']
     # Remove user from leader list if there
    if my_id in leader_list:
        leader_list.remove(my_id)
        alliances_model.update_leader_of_alliance(alliance['shortname'], leader_list)```

removes users just fine and the check is in place for when users are kicked and people manually leave.

**Comment by shibdib** [comment]
Going to re-PR this with the permissions portion commented out until I can sort it.

**Pull request closed without merging**
