### PR TITLE
add ability to remove users from alliance

### PR DESCRIPTION
**Pull request by RvstFyth**
Functionality for removing alliance members.
This code comes from shibdibs repository. 

This is without all the leader and alliance messaging functionality

### CODE REVIEW

**Comment by RvstFyth** [comment]
Valid points. I will fix them later today.

**Comment by qgazq** [comment]
Retested with changes, and it still works.
I tried negative cases as well, and all seem to work.

An odd one is the first test (not being in an alliance yourself, which is the same for the other actions, so is consistent) that it just returns the error rather than it being a flash on the alliance page.  This means it just gets a blank page with that text on.  I guess this is because it's not a case you should be able to get to (you only get the kick form if you're in an alliance).  To test I had the form up twice, kicked myself from one (that worked) then tried to kick someone else from the other.  It successfully gave the error but on a blank page.
As this is not an expected error, and it's consistent with the other actions, and it still "works" I wouldn't suggest changing it.

**Comment by qgazq** [comment]
Another minor point I've just realised (when trying to add myself back into my test alliance from the database) my username is QGazQ, but was able to kick myself as qgazq.  This is because user_id_from_db uses LOWER on both params.  Therefore the "NAME IS CASE SENSITIVE" isn't true on the kick now the api check has been removed.
I wouldn't suggest removing it though unless you really want to, as it would make the forums look odd!

**Comment by RvstFyth** [comment]
Just tested that and you are right. But i'm not going to change it for now, as i will create a separate manage members section after this gets merged.
Thank you for testing and the feedback!

**Pull request merged**
